import process from 'node:process';
import commonjs from '@rollup/plugin-commonjs';
import typescript from '@rollup/plugin-typescript';
import postcssImport from 'postcss-import';
import copy from 'rollup-plugin-copy';
import del from 'rollup-plugin-delete';
import postcss from 'rollup-plugin-postcss';
import postcssPresetEnv from 'postcss-preset-env';
import nodeResolve from '@rollup/plugin-node-resolve';

/* ------------------------------------ - ----------------------------------- */

const isProduction = process.env.BUILD === 'production';
const PLUGIN_DIR =
	'../../test-vault/.obsidian/plugins/obsidian-fountain-editor';
const OUT_DIR = 'build';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source, visit the plugin's github repository
*/
`;

const jsConfig = {
	input: 'src/main.ts',
	external: ['obsidian', '@codemirror/view', '@codemirror/state'],
	output: {
		dir: OUT_DIR,
		sourcemap: 'inline',
		format: 'cjs',
		sourcemapExcludeSources: isProduction,
		exports: 'default',
		banner: isProduction ? banner : undefined,
	},
	plugins: [
		// Postcss({
		// 	extensions: [".css"],
		// 	minimize: true,
		// 	extract: path.resolve("HELP.css"),
		// 	sourceMap: !isProduction,
		// }),
		nodeResolve(),
		typescript({
			sourceMap: !isProduction,
			inlineSources: !isProduction,
			rootDir: './src',
		}),
		commonjs(),
		copy({
			targets: [{ src: 'manifest.json', dest: OUT_DIR }],
			hook: 'writeBundle',
			// Verbose: true,
			overwrite: true,
		}),

		del({
			targets: PLUGIN_DIR + '/*',
			runOnce: true, // Only run once per build
			hook: 'buildStart',
			verbose: true,
			force: true, // Force deletion to avoid issues with read-only files
		}),
		copy({
			targets: [{ src: 'build/*', dest: PLUGIN_DIR }],
			hook: 'writeBundle',
			overwrite: true,
		}),
		!isProduction &&
			copy({
				targets: [{ src: '.hotreload', dest: PLUGIN_DIR }],
				copyOnce: true, // Only copy once per build
				hook: 'writeBundle',
				overwrite: true,
			}),
	],
};

const cssConfig = {
	input: 'src/styles/index.css',
	output: { file: OUT_DIR + '/styles.css' },
	plugins: [
		postcss({
			extract: true,
			sourceMap: !isProduction,
			plugins: [postcssImport(), postcssPresetEnv()],
		}),
		copy({
			targets: [{ src: 'build/*', dest: PLUGIN_DIR }],
			hook: 'writeBundle',
			overwrite: true,
		}),
	],
};

const config = [cssConfig, jsConfig];
export default config;
