blank_issues_enabled: false
contact_links:
  - name: 💡 Ideas for New Features + Improvements
    url: https://github.com/chuangcaleb/obsidian-fountain-editor/discussions/new/choose
    about: Propose and discuss future improvements
